language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build

deploy:
  provider: pages:git
  skip_cleanup: true
  token: $TRAVIS_GITHUB_TOKEN
  edge: true
  local_dir: dist
  on:
    branch: master